version: '3.8'

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Vector Database API
  vector-api:
    build: .
    container_name: vector-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Server Configuration
      - PORT=8080
      - HOST=0.0.0.0
      - NODE_ENV=production
      
      # API Security
      - API_KEY=${API_KEY}
      
      # Qdrant Configuration
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=${QDRANT_COLLECTION:-my_docs}
      - QDRANT_VECTOR_SIZE=${QDRANT_VECTOR_SIZE:-1536}
      - QDRANT_DISTANCE=${QDRANT_DISTANCE:-Cosine}
      
      # MongoDB Configuration
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
      - MONGO_CHANGE_STREAMS_ENABLED=${MONGO_CHANGE_STREAMS_ENABLED:-false}
      - MONGO_READ_ONLY=${MONGO_READ_ONLY:-true}
      
      # Embeddings Configuration
      - EMBEDDINGS_PROVIDER=${EMBEDDINGS_PROVIDER:-openai}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Google Sheets Integration
      - GCP_SERVICE_ACCOUNT_JSON=${GCP_SERVICE_ACCOUNT_JSON}
      - SHEET_ID=${SHEET_ID}
      - GOOGLE_SHEETS_SYNC_ENABLED=${GOOGLE_SHEETS_SYNC_ENABLED:-true}
      - GOOGLE_SHEETS_SYNC_INTERVAL_MINUTES=${GOOGLE_SHEETS_SYNC_INTERVAL_MINUTES:-60}
      
      # Optional: pgvector support
      - PGVECTOR_ENABLED=${PGVECTOR_ENABLED:-false}
      - DATABASE_URL=${DATABASE_URL:-}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
      
      # Rate Limiting
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-60}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-60000}
      
      # CORS Configuration
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
    
    depends_on:
      qdrant:
        condition: service_healthy
    
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  qdrant_data:
    driver: local

networks:
  default:
    name: vector-network
